# Generated by Django 5.2.3 on 2025-07-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='predefined_type',
            field=models.CharField(blank=True, choices=[('hand_tools', 'Hand Tools'), ('power_tools', 'Power Tools'), ('cordless_tools', 'Cordless Tools')], max_length=20, null=True),
        ),
    ]
