# Generated by Django 5.2.3 on 2025-07-31 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_predefined_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='predefined_type',
        ),
    ]
