# Generated by Django 5.2.3 on 2025-08-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
