# Generated by Django 5.2.3 on 2025-07-04 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0004_alter_tool_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('maintenance_type', models.CharField(max_length=100)),
                ('performed_by', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='tools.tool')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
