# Generated by Django 5.2.3 on 2025-07-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolmaintenance',
            name='maintenance_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='toolmaintenance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toolmaintenance',
            name='performed_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
