# Generated by Django 5.2.3 on 2025-08-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_toolmaintenance_maintenance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolmaintenance',
            name='notes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
