# Generated by Django 5.2.3 on 2025-07-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_room_tool_section_alter_tool_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='files'),
        ),
    ]
