# Generated by Django 5.2.3 on 2025-07-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_alter_tool_brand_name_alter_tool_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='tracking_number',
            new_name='inventory_number',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='section',
            new_name='section_number',
        ),
    ]
