# Generated by Django 5.2.3 on 2025-07-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_rename_tracking_number_tool_inventory_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='section_number',
            field=models.CharField(max_length=20),
        ),
    ]
